### ISSUE TITLE
how can i use this in onRequest point?

### ISSUE THREAD

**Issue by xycloud** [jsumners/hapi-easy-session#2]
how can i use this in onRequest point

**Comment by jsumners** [comment]
I don't know what you are trying to ask.

On Wednesday, June 1, 2016, xycloud notifications@github.com wrote:

> how can i use this in onRequest point
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/jsumners/hapi-easy-session/issues/2, or mute the
> thread
> https://github.com/notifications/unsubscribe/AATmsTHzsS7H7ULZMnYNX_WXPOjky2myks5qHkT7gaJpZM4IsKKJ
> .

## 

James Sumners
http://james.sumners.info/ (technical profile)
http://jrfom.com/ (personal site)
http://haplo.bandcamp.com/ (music)

**Comment by xycloud** [comment]
sorry. let me explain, let me show you code:

first I register this lib like below:

```
  server.register({
    register: require('hapi-easy-session'),
    options: {
      cache: { segment: 'session' },
      cookie: { isSecure: false },
      key: 'super-secret-cookie-encryption-key'
  }}, (err) => {});
```

 and I set the views at onRequest point:

```
server.ext('onRequest', function(request, reply) {
   request.ssesion.views = request.session.views + 1 || 1; 
   return reply.continue();
}

```

add router:

```
server.route({
  method: 'GET',
  path: '/',
  handler: function(request, reply) {
    console.log(request.session.views);
    return reply('hihihi');
  }
});
```

##but when i access '/', the request.session.views is always NaN

**Comment by jsumners** [comment]
Look at the request life cycle -- http://hapijs.com/api#requests

`onRequest` is called prior to any cookies being processed. This extension relies on a cookie being present to identify the client and lookup their session. Thus, this extension starts in `onPreAuth`, which is the first available extension point after cookie processing.

I'd suggest you use the `onPostAuth` extension point to track your views. It makes a bit more sense anyway, because without "authorization" (anonymous or otherwise) it's not really a "view".
